spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:h2:mem:testdb3
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console